frameworkVersion: '3'
service: aws-simple-api

plugins:
  - serverless-webpack

custom:
  stage: ${opt:stage}

provider:
  name: aws
  runtime: nodejs16.x

functions:
  api:
    handler: functions/api.handler
    role: ApiRole
    environment:
      TABLE_USERS: ${self:custom.stage}-Users
    events:
      - httpApi: '*'

resources:
  - ${file(resources/iam.yml)}
  - ${file(resources/dynamodb.yml)}
