Resources:
  DynamoTableUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.stage}-Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  DynamoTableUsers:
    Value:
      Ref: DynamoTableUsers
